<h1>StackExchange Authorization</h1>
<?php echo $this->__('Connect your Stackexchange user account for maximum experience of MageStackDay :-) '); ?>

<form action="<?php echo $this->getUrl('*/*/authenticate') ?>" method="post" id="form-validate" class="scaffold-form">
    <div class="buttons-set">
        <p class="back-link"><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
        <button type="submit" title="<?php echo $this->__('Authorize Stackexchange Account') ?>" class="button">
            <span>
                <span><?php echo $this->__('Connect Stackexchange Profile') ?></span>
            </span>
        </button>
    </div>
</form>